# Generated by Django 5.2.5 on 2025-09-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=150)),
                ('año_lanzamiento', models.IntegerField()),
                ('sinopsis', models.TextField()),
            ],
        ),
    ]
